#!/bin/bash
set -e

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

IMAGE_ID=$(tar c $HERE/image/ 2>/dev/null | sha1sum | awk '{print $1}')

if ! container image inspect kernel:$IMAGE_ID >/dev/null 2>/dev/null; then
	pushd $HERE/image >/dev/null
	container build -t kernel:$IMAGE_ID
	if container image inspect kernel:latest >/dev/null 2>/dev/null; then
		OLD=$(container image inspect kernel:latest | jq '.[0]["index"]["annotations"]["org.opencontainers.image.ref.name"]' -r)
		container image rm kernel:latest
		container image rm kernel:$OLD
	fi
	container image tag kernel:$IMAGE_ID kernel:latest
	popd >/dev/null
fi

if ! container volume inspect kernel-data >/dev/null 2>/dev/null; then
	container volume create kernel-data
fi

[[ $BUILD_ONLY == 1 ]] && exit 0

exec container run \
	--rm -it \
	--memory 16G \
	--cpus 10 \
	--virtualization \
	--cap-add ALL \
	-v $HOME:$HOME \
	-v kernel-data:/data/ \
	-v /Volumes/src:/Volumes/src \
	-e DEV_HOME=$HOME \
	-e DEV_USER=$(id -u -n) \
	-e DEV_UID=$(id -u) \
	-e DEV_GID=$(id -g) \
	-e SHELL=$SHELL \
	--name $(hostname -s)-kernel \
	-w $(pwd) \
	kernel:$IMAGE_ID
